### PR TITLE
Added multiple qr code support

### PR DESCRIPTION
**Pull request by luvnishCapgemini**

### CODE REVIEW

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini multiple QR code is working in android? please reply so we can close this PR asap.

**Review by pushpender-singh-ap — APPROVED** [review]
LGTM

**Comment by luvnishCapgemini** [comment]
@pushpender-singh-ap 
Thank you for the approval. Can you launch a new version so that I could remove patch from local?

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini Today i will release new version.

**Comment by pushpender-singh-ap** [comment]
@luvnishCapgemini Patch version is release.

**Comment by luvnishCapgemini** [comment]
thank you @pushpender-singh-ap 
Really appreciate for your hard work.

**Pull request merged**
